config/routes.rb
Rails.application.routes.draw do

  

  root 'home#index'
  get 'appointments/monthly_calendar'
  get 'appointments/weekly_calendar'
  get 'appointments/daily_schedule'
  resources :appointments do
    member do
      patch :approved
    end
  end
  get 'home/index'

  get 'home/about'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  
  resources :users
  resources :sessions

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
	  #before_validation :save_contact_number


	belongs_to :user
	has_many :categorizations
	has_many :categories, through: :categorizations
	#has_and_belongs_to_many :categories, :join_table => "appointments_categs"

	validates :date, presence: true
	validates :hour, presence: true
 	validates :minute, presence: true
 	#validates :category_id, presence: true
	validates :contact_number,  presence: true, format: { with: /09[0-9]{2}-[0-9]{3}-[0-9]{4}/,  message: "Format should be (09xx-xxx-xxxx)" }
	#validates :contact_number, allow_blank: false
	# end

	#scopes
  	# scope :unapprovedd, -> { where(approved: nil)} 
  	scope :unapprovedd, ->{ where(approved: false)}
  	scope :approvedd, -> { where(approved: true ) }
  	scope :valid, -> { where("date >= ?", Date.current ) }

	#def
 	# private
	
	# end

	def approved_app?
  		approved != nil && approved != false
	end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy, :approved]
  before_action :authenticate_user!


  # GET /appointments
  # GET /appointments.json
  def index
    # if current_user
      if current_user.admin? || current_user.staff?
        @appointments = Appointment.all.order("date")
      elsif current_user
        @appointments = current_user.appointments.order("date")
      else 
        redirect_to root_path
      end
    # else
    #   redirect_to root_path
    # end

  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
     if @appointment.user_id == current_user.id
    elsif  current_user.admin? || current_user.staff?

    else
      redirect_to root_path

    end
  end

  def monthly_calendar
    if current_user.staff? || current_user.admin?
      @appointments = Appointment.all.order("date").order("hour")
    else 
      redirect_to appointments_path
    end
  end

  def daily_schedule
    if current_user.staff? || current_user.admin?
      @appointments = Appointment.where("date >= :start_date AND date <= :end_date", {start_date: params[:start_date], end_date: params[:end_date]}).order("date").order("hour")
    else 
      redirect_to appointments_path
    end
  end

  def weekly_calendar
    if current_user.staff? || current_user.admin?
      @appointments = Appointment.all.order("date").order("hour")
    else
      redirect_to appointments_path
    end
  end
  # GET /appointments/new
  def new
    if current_user.guest == true
      @appointment = Appointment.new
    else
      @appointment = Appointment.new :contact_number => current_user.contact_number
    end
  end

  # GET /appointments/1/edit
  def edit
    if @appointment.user_id == current_user.id && current_user.admin == false && current_user.staff == false
      if @appointment.approved?
        redirect_to appointments_path
        flash[:notice] = "Cannot edit approved appointments, Please Contact staff for changes"
      end
    elsif  current_user.admin? || current_user.staff?

    else
      redirect_to root_path

    end
  end



  def approved
    #CarsTodoMailer.ready_for_pickup(@appointment).deliver
    if current_user.admin? || current_user.staff?
      @appointment.update_attribute(:approved, true)
      AppointmentMailer.approved_appointment(@appointment).deliver_later
      redirect_to @appointment, notice: "Appointment has been approved."
    else 
      redirect_to root_path
    end
  end   

  # POST /appointments
  # POST /appointments.json
  def create
    if current_user.admin == true
        @appointment = Appointment.new(appointment_params)
        @appointment.save(validate: false)
        redirect_to @appointment, notice: 'Appointment was successfully created.'
    else

      
      @appointment = current_user.appointments.build(appointment_params)

      respond_to do |format|
        if @appointment.save
          @appointment.contact_number = current_user.contact_number
          AppointmentMailer.new_appointment(@appointment).deliver_later
          format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
          format.json { render :show, status: :created, location: @appointment }
        else
          format.html { render :new }
          format.json { render json: @appointment.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    # if current_user.guest? && @appointment.contact_number.blank?
    #   respond_to do |format|
    #     format.html { render :new, notice: "Guest Users should provide contact Number" }
    #   end
    # end
  
      @appointment.update_attributes(appointment_params)
      respond_to do |format|
        if @appointment.update(appointment_params)
          format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
          format.json { render :show, status: :ok, location: @appointment }
        else
          format.html { render :edit }
          format.json { render json: @appointment.errors, status: :unprocessable_entity }
        end
      end
   
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment = current_user.appointments.find(params[:id])
    if @appointment.approved? && current_user.admin == false && current_user.staff == false
        redirect_to @appointment, notice: "Appointment that has been approved cannot be deleted, please contact staff/admin to delete."


    else 
      @appointment.destroy
        respond_to do |format|
          format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
          format.json { head :no_content }
        end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # def save_contact_number
    #     @appointment.contact_number = current_user.contact_number
    # end
    # Never trust parameters from the scary internet, only allow the white list through.
 
    def appointment_params
      params.require(:appointment).permit(:date, :hour, :minute, :user_id, :approved,:current_user ,:contact_number, :note, :category_ids => [])
    end

    # def save_contact_number
    #   @current_user.contact_number = current_user.contact_number
    #   self.contact_number = current_user.contact_number
    # end


end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_calendar_toggle.html.erb
<div class="well" %>
<li><%= link_to 'Monthly Calendar', appointments_monthly_calendar_path %></li>
<li><%= link_to 'Weekly Calendar', appointments_weekly_calendar_path %></li>
<li><%= link_to 'Appointments Home', appointments_path %></li>

</div>

app/views/appointments/_form.html.erb
<%= simple_form_for @appointment, html: { multipart: true} do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
   <h2>appointment <unsuccessful></unsuccessful>, 
     there is/are <%= pluralize(@appointment.errors.count, "error") %>.</h2>
     prevented this appointment from saving

       <% @appointment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    </div>
<% end %> 
  <div class="form-inputs">
  <h3>Date</h3>
    <%= f.date_field :date, min: Date.today+1.day %>
  </div>
  <h3>Time</h3>
  <div id="time-div">
    <%= f.input :hour, collection: 9..18, label: false %>&nbsp;&nbsp; : &nbsp;&nbsp;
    <%= f.input :minute, collection: ['00','15','30','45'], label: 
    false %>  
  </div>
  <div class="form-inputs">
   <%= f.association :categories, :as => :check_boxes, label: "Services To Be Availed" %>
   </div> 

      <%= f.input :contact_number, required: true, :as => :hidden %>
  
   <% if current_user.staff == true ||current_user.admin == true %>
      <%= f.association :user, :label_method => :email, :value_method => :id %>
      <%= f.input :approved %>
      <%= f.input :note %>
      <% end %>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/appointments/daily_schedule.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Appointments</h1>
<%= form_tag appointments_daily_schedule_path, :method => 'get' do %>
  <%= date_field_tag :start_date, params[:start_date] %>
  <%= date_field_tag :end_date, params[:end_date] %>
  <%= submit_tag "Search " %>
<% end %>
<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Hours</th>
      <th>Minutes</th>
      <th>Approved</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.date %></td>
        <td><%= appointment.hour %></td>
        <td><%= appointment.minute %></td>
        <td><%= appointment.approved %></td>
        <td><%= appointment.user .try(:email)%></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Delete', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>
<% if current_user.admin? || current_user.staff? %>
<%= render 'calendar_toggle' %>

  <div class="panel">
  <div class="panel panel-info">
  <div class="panel-heading">
    <h3>Unapproved Appointments</h3>
    </div>

    <div class="panel-body">
    <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Hour</th>
          <th>Minute</th>
          <th>User</th>
          <th>Approved</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @appointments.select{ |m| m.approved != true }.each do |appointment| %>
          <tr>
            <td><%= appointment.try(:date) %></td>
            <td><%= appointment.hour %></td>
            <td><%= appointment.minute %></td>
            <td><%= appointment.user.try(:first_name) %></td>
            <td><%= appointment.approved %></td>
            <td><%= link_to 'Show', appointment %></td>
            <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
            <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
    </div>
    </div>
    </div>
    <div class="panel-group">
      <div class="panel panel-primary">
        <div class="panel-heading">
           <h3>Approved Appointments Today</h3>
        </div>

    <div class="panel-body">
    <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Hour</th>
          <th>Minute</th>
          <th>User</th>
          <th>Approved</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @appointments.select{ |m| m.approved == true }.each do |appointment| %>
          <tr>
            <td><%= appointment.date %></td>
            <td><%= appointment.hour %></td>
            <td><%= appointment.minute %></td>
            <td><%= appointment.user.try(:first_name) %></td>

            <td><%= appointment.approved %></td>
            <td><%= link_to 'Show', appointment %></td>

            <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
            <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
</div></div>
    </div>
    <br>

    <%= link_to 'New Appointment', new_appointment_path, class: "btn btn-default"  %>

<% else %>

<!-- list of appointments for each user -->
<h1>Appointments</h1>


       
    <div class="panel-group">
      <div class="panel panel-info">  
        <div class="panel-heading"> 
        Waiting:    <!--<%= @appointments.unapprovedd.valid %>-->
        </div>
            <div class="panel-body"> 
              <% @appointments.unapprovedd.valid.each do |appointment| %>
              <% if current_user.id == appointment.user_id %>
              <p><strong>Date: <%= appointment.date.strftime(" %B-%d-%Y") %></p>
              <p>Time:  <%= appointment.hour %>:<%= appointment.minute %></p>
              <p>User: <%= appointment.user.first_name %></p>
            
             
                

                  <%= link_to 'Edit', edit_appointment_path(appointment) %>
                  <%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %>
                 
               <hr>
               <% end %>
               <% end %>
            </div>
      </div>
    </div>

       <div class="panel-group">
      <div class="panel panel-primary">  
        <div class="panel-heading"> 
        Approved:   <!--<%= @appointments.unapprovedd.valid %>-->
        </div>
            <div class="panel-body"> 
              <% @appointments.approvedd.valid.each do |appointment| %>

               <% if current_user.id == appointment.user_id %>

              <p><strong>Date:</strong> <%= appointment.date.strftime(" %B-%d-%Y") %></p>
              <p><strong>Time:</strong>  <%= appointment.hour %>:<%= appointment.minute %></p>
              <p><strong>User:</strong> <%= appointment.user.first_name %></p>
              
               <%= link_to 'Show', appointment %>
                

                  <%= link_to 'Edit', edit_appointment_path(appointment) %>
                
                  <%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %>
                
               <hr>
               <% end %>
               <% end %>
            </div>
      </div>
    </div>

<br>


<%= link_to 'New Appointment', new_appointment_path, class: "btn btn-default" %>

<br>
<br>
<br>
<br>
<br>

<% end %>

app/views/appointments/monthly_calendar.html.erb
<%= render 'calendar_toggle' %>

    <div class="container">
    <section id="Calendar">

        <h3>Monthly Calendar </h3>

        <% start_date = params.fetch(:start_date, Date.today).to_date %>
        <% date_range = (start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week).to_a %>
        <%= link_to "Previous Month", start_date: date_range.first - 1.day, class: "btn btn-default" %> ||
        <%= link_to "Next Month", start_date: date_range.last + 1.day, class: "btn btn-primary", class: "btn btn-default" %>
        <%= link_to 'Book Appointment', new_appointment_path, class: "btn btn-default", style: "float:right;" %>
            <h3><%= I18n.t("date.month_names")[start_date.month] %> <%= start_date.year %></h3>
            <table class="table table-hover"> 
            
              
          
              <thread>
                <tr>  
                  <% date_range.slice(0, 7 ).each do |day| %>
                    <th class="week_day"> <%= I18n.t("date.day_names")[day.wday]%></th>
                  <% end %>
                </tr>
              </thread>
              <tbody>
                <% date_range.each_slice(7) do |week| %>
                  <tr>
                  <% week.each do |day| %>
                   <td class="date_number">
                    <%= day.strftime("%B %d") %>
                        <!--matching of the appointment date and the calendar-->
                       
                         
                                <% @appointments.select{ |m| m.date == day }.each do |appointment| %>
                                   <div id="appointmentlinks"><%= link_to appointment.user.try(:hour), appointment %> </div>
                                <% end %>
                         
                      
                   </td>
                  <% end %>
                </tr>
                <% end %>
              </tbody>
            </table> <%= @appointments.count %>
            
    </section>


    </div>
       

    </table>
    <!-- end of calendar -->

app/views/appointments/new.html.erb
<div class="well">
<h1>New Appointment</h1>

<%= render 'form' %>
<hr> 
<%= link_to 'Back', appointments_path, class: 'btn btn-default' %>

</div>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>
<div class="panel-group">
  <div class="panel panel-primary">
    <div class="panel-heading">
      Appointment Id # [<%= @appointment.id %>]
    </div>
    <div class="panel-body"
      <p>
        <strong>Date :</strong>
        <%= @appointment.date %>
      </p>

      <p>
        <strong>Time :</strong>
        <%= @appointment.hour %>  :   <%= @appointment.minute %>
      </p>
      <p>
      <strong> Services to be Availed :</strong>
      <ul>
       <% @appointment.categorizations.each do |cat|  %>
        
        <li><%=  cat.category.name %></li>
          
       
       <% end %>

        </ul>

      </p>
         

      <p>
        <strong>Status :</strong>
     
        <% if @appointment.approved_app?%>
           <font style="color: green">
          Approved
          </font>
          Waiting for Confirmation
        <% end %>
      </p>

      <% if @appointment.user.try(:guest?) %>
      <p>
        <strong>Contact Number :</strong>
        <%= @appointment.contact_number %>

      </p>
      	
      <% end %>
          <% if current_user.admin? || current_user.staff? %>
             <p>
            <strong> Contact info: </strong>
            <%= @appointment.user.try(:contact_number) %> /  <%= @appointment.try(:contact_number) %>
            </p>
            <p>
           <strong> Note : </strong>
           </p>
           <p>
            <%= simple_format(@appointment.note) %> 
            </p>
              <% if @appointment.approved_app?%>
              <p>
                  <%= link_to "Marked as Approved", approved_appointment_path(@appointment.id), method: :patch, data: {confirm: "Are you Sure you want to mark appointment Approved??"},class: "btn btn-primary disabled"  %>
              <% else %>
                  <%= link_to "Mark as Approved", approved_appointment_path(@appointment.id), method: :patch, data: {confirm: "Are you Sure you want to mark appointment Approved??"},class: "btn btn-primary", id: "approve_button" %>
              <% end %>

          </p>
          <% end %>
      <% if current_user.admin? || current_user.staff? %>
      <hr>
      <%= link_to 'Edit', edit_appointment_path(@appointment), class: 'btn btn-default' %> 
      <% end %>
      <%= link_to 'Back', appointments_path, class: 'btn btn-default' %>
      </div>
      </div>
</div>

app/views/appointments/weekly_calendar.html.erb
<%= render 'calendar_toggle' %>
  <!-- start of calender -->


    <div class="container">
      <div class="well">
    <section id="Calendar">

        <h3> Weekly Calendar </h3>
        <%= link_to 'Current Week', appointments_weekly_calendar_path, class: 'btn btn-default' %><br>
        <% start_date = params.fetch(:start_date, Date.today).to_date %>
        <% date_range = (start_date.beginning_of_week..start_date.end_of_week).to_a %>
        <%= link_to 'Previous Week', start_date: date_range.first - 1.day, class: 'btn btn-default' %> ||
        <%= link_to 'Next Week', start_date: date_range.last + 1.day, class: "btn btn-default" %>
        <%= link_to 'Book Appointment', new_appointment_path, class: "btn btn-default", style: "float:right;" %>
            <h3><%= I18n.t("date.month_names")[start_date.month] %> <%= start_date.year %></h3>
            <table class="table table-hover"> 
            
              
          
              <thead>
                <tr>  
                  <th> Time </th>
                  <% date_range.slice(0, 7 ).each do |day| %>
                    
                    <th class="week_day"><%= day.strftime("%B %d") %><br> <%= I18n.t("date.day_names")[day.wday]%>
                       
                    </th>

                  <% end %>
                </tr>
              </thead>
              <tbody>
                <% date_range.each_slice(7) do |week| %>
                  <tr>
                  <% week.each do |day| %>
                   <td class="date_number">
                  
                        <!--matching of the appointment date and the calendar-->
                       
                         
                                <% @appointments.select{ |m| m.date == day }.each do |appointment| %>
                                   <div id="appointmentlinks"><%= appointment.try(:date).strftime("%B %d") %> <%= link_to appointment.try(:hour), appointment%> </div>
                                <% end %>
                         
                      
                   </td>
                  <% end %>
                </tr>
                <% end %>
              </tbody>
            </table> <%= @appointments.count %>
            
    </section>



       

    </table>
        </div>
        </div>
    </div>
    <!-- end of calendar -->