config/routes.rb
Rails.application.routes.draw do

  

  root 'home#index'
  get 'appointments/monthly_calendar'
  get 'appointments/weekly_calendar'
  get 'appointments/daily_schedule'
  resources :appointments do
    member do
      patch :approved
    end
  end
  get 'home/index'

  get 'home/about'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  
  resources :users
  resources :sessions

end

app/views/layouts/_brandsnavbar.html.erb
    <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Brands <span class="caret"></span></a>
              <ul class="dropdown-menu">
             
              <% Brand.all.published.each do |brand| %>
   <li> <%= link_to brand.name, products_path(brand: brand.name) %></li>
    <% end %> </ul>

app/views/layouts/_footer.html.erb
<footer class="footer-section ">
  <div class="row">
        
      <div class="soc-net social-links">
    </a>
          </div>
    
    <div class="copyrights">
    <ul class="footer">

    <li class="partnericons"> <p class="copyrightss">  ©  <%= Time.now.year %> <%= link_to "HEADS by volu-med ", "http://www.hairs.ph", target: "_blank", rel: "nofollow" %>| All Rights Reserved   </p>
  	<p class="introtoicons">
  	In Partnership with : 
  	
    <%= image_tag("bedhead.png") %>


    <%= image_tag("davines.png") %>
     </p>
    </li>
    
    </ul>

</div>
   
  </div>
</footer><!-- .footer-section -->
    <!--Footer-->

app/views/layouts/_header.html.erb
<div class="navbar-wrapper">
<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
    
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("logo.png") , root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="navbar-right">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li><%= link_to "About", home_about_path %></li>
     
 
        <li><%= link_to "Calendar & Appointments", appointments_path %></li>
   
       
         
           <ul class="nav navbar-nav navbar-right">
    
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
           <ul class="dropdown-menu">
                     <% if current_user %>
                       <li> Logged in as <%= current_user.email_loggedin %>.</li>
                        <% if current_user.guest? %>
                          <li><%= link_to "Become a Member", sign_up_path %></li>
                        <% else %>
                         <li> <%= link_to "Log out", log_out_path %></li>
                        <% end %>


                      <% else %>
                       <li> <%= link_to "Sign up", sign_up_path %> </li>
                        <li><%= link_to "Log In", log_in_path %></li>
                        <% if current_user.nil? %>

    <li><%= link_to "Book Appointment as A Guest", users_path, method: :post %> </li>
<% end %> 
                      <% end %>
                </ul>
        </li>
      </ul>
          
      </ul>
     
 
  
    
        
               
  
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Heads by volumed</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<div id="user_nav">

</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<body class="<%= yield(:bg_style) %>">
  <%= render "layouts/header" %>
    <div class="container">

      <%= yield %>
      <%= render "layouts/product_partners" %>
    </div>
    <%= render "layouts/footer" %>
</body>
</html>